/** Реестр персонажей «Дым над льдом» — источник для контактов, ГИБДД, карт. */
const CHARACTERS = [
  {
    id: 'sergey',
    fullName: 'Акунин Сергей Павлович',
    contactName: 'Сергей Акунин',
    birthDate: '1986-02-11',
    age: 39,
    status: 'очевидный подозреваемый',
    profession: 'ведущий риэлтор агентства «Золотой квадрат», бывший спортсмен',
    address: 'г. Новоград, ул. Заречная, д. 12',
    phone: '+7 (903) 555-12-86',
    email: 'akunin.s@zk-invest.ru',
    avatar: 'С',
    plate: 'А316СК 152',
    car: 'Volkswagen Passat',
  },
  {
    id: 'anna',
    fullName: 'Акунина Анна Павловна',
    contactName: 'Анна Акунина',
    birthDate: '1983-05-17',
    age: 42,
    status: 'жертва',
    profession: 'владелица риэлторского агентства «Золотой квадрат»',
    address: 'г. Новоград, ул. Заречная, д. 12',
    phone: '+7 (903) 110-05-83',
    email: 'anna@zk-invest.ru',
    avatar: 'А',
    plate: 'М042АН 152',
    car: 'Hyundai Santa Fe',
  },
  {
    id: 'veronika',
    fullName: 'Пронина Вероника Алексеевна',
    contactName: 'Вероника Пронина',
    birthDate: '1997-11-29',
    age: 27,
    status: 'жертва до смерти Анны',
    profession: 'недавняя выпускница вуза',
    address: 'г. Новоград, ул. Молодёжная, д. 5, кв. 47',
    phone: '+7 (903) 290-11-97',
    email: '',
    avatar: 'В',
    plate: 'Е907ВА 152',
    car: 'LADA Granta',
  },
  {
    id: 'zhanna',
    fullName: 'Приходько Жанна Валентиновна',
    contactName: 'Жанна Приходько',
    birthDate: '1989-07-22',
    age: 36,
    status: 'ложная визуальная связка',
    profession: 'требует уточнения',
    address: 'г. Новоград, ул. Школьная, д. 14, кв. 27',
    phone: '+7 (903) 220-07-89',
    email: '',
    avatar: 'Ж',
    plate: 'К558ЕН 152',
    car: 'Renault Logan',
  },
  {
    id: 'viktor',
    fullName: 'Иванов Виктор Иванович',
    contactName: 'Виктор Иванов',
    birthDate: '1988-01-08',
    age: 37,
    status: 'серийный убийца',
    profession: 'врач-офтальмолог клиники ProЗрение',
    address: 'г. Новоград, ул. Строителей, д. 11, кв. 74',
    phone: '+7 (903) 080-01-88',
    email: 'ivanov.v@prozrenie.ru',
    avatar: 'В',
    plate: 'В744КТ 152',
    car: 'Skoda Octavia',
  },
  {
    id: 'natalia',
    fullName: 'Иванова Наталья Вячеславовна',
    contactName: 'Наталья Иванова',
    birthDate: '1988-03-26',
    age: 37,
    status: 'подозреваемая / источник доступа',
    profession: 'начальница ProЗрение',
    address: 'г. Новоград, ул. Строителей, д. 11, кв. 74',
    phone: '+7 (903) 260-03-88',
    email: 'ivanova.n@prozrenie.ru',
    avatar: 'Н',
    plate: 'О219НА 152',
    car: 'LADA Largus',
  },
  {
    id: 'kristina',
    fullName: 'Фомина Кристина Петровна',
    contactName: 'Кристина Фомина',
    birthDate: '2000-03-03',
    age: 25,
    status: 'ложный подозреваемый',
    profession: 'офис-менеджер / секретарь Анны; сотрудница ProЗрение',
    address: 'г. Новоград, ул. Студенческая, д. 9, кв. 41',
    phone: '+7 (903) 030-03-00',
    email: 'fomina@zk-invest.ru',
    avatar: 'К',
    plate: 'Т386КР 152',
    car: 'Kia Rio',
  },
  {
    id: 'igor',
    fullName: 'Волков Игорь Михайлович',
    contactName: 'Игорь Волков',
    birthDate: '1987-01-30',
    age: 38,
    status: 'свидетель',
    profession: 'архитектор',
    address: 'г. Новоград, ул. Инженерная, д. 15, кв. 34',
    phone: '+7 (903) 310-01-87',
    email: 'volkov.arch@mail.ru',
    avatar: 'И',
    plate: 'Р511ОВ 152',
    car: 'Renault Duster',
  },
  {
    id: 'artur',
    fullName: 'Скорый Артур Максимович',
    contactName: 'Артур Скорый',
    birthDate: '1991-09-05',
    age: 33,
    status: 'журналист',
    profession: 'журналист криминальной колонки',
    address: 'г. Новоград, ул. Печатная, д. 8, кв. 15',
    phone: '+7 (916) 440-12-08',
    email: 'a.skory@media.ru',
    avatar: 'А',
    plate: 'С204АС 152',
    car: 'Mercedes-Benz C 180',
  },
  {
    id: 'likhachev',
    fullName: 'Лихачев Антон Сергеевич',
    contactName: 'Антон Лихачев',
    birthDate: '1990-06-25',
    age: 35,
    status: 'ложный подозреваемый',
    profession: 'бывший сотрудник «Золотого квадрата»',
    address: 'г. Новоград, ул. Промышленная, д. 11, кв. 27',
    phone: '+7 (903) 250-06-90',
    email: '',
    avatar: 'А',
    plate: 'Х617АК 152',
    car: 'Volkswagen Tiguan',
  },
  {
    id: 'tikhonov',
    fullName: 'Тихонов Евгений Фёдорович',
    contactName: 'Евгений Тихонов',
    birthDate: '1976-10-14',
    age: 48,
    status: 'ложный / полуложный мотивный узел',
    profession: 'крупный бизнесмен, бывший наставник Анны',
    address: 'г. Новоград, ул. Набережная, д. 15, кв. 201',
    phone: '+7 (903) 140-10-76',
    email: 'tikhonov@invest-group.ru',
    avatar: 'Е',
    plate: 'М888ЕТ 152',
    car: 'Toyota RAV4',
  },
  {
    id: 'pavel',
    fullName: 'Левин Павел Евгеньевич',
    contactName: 'Павел Левин',
    birthDate: '1996-04-04',
    age: 29,
    status: 'преследователь Анны',
    profession: 'требует уточнения',
    address: 'г. Новоград, ул. Северная, д. 8, кв. 19',
    phone: '+7 (903) 040-04-96',
    email: '',
    avatar: 'П',
    plate: 'У043РА 152',
    car: 'LADA Vesta',
  },
  {
    id: 'miya',
    fullName: 'Тищенко Мия Андреевна',
    contactName: 'Мия Тищенко',
    birthDate: '1996-04-12',
    age: 29,
    status: 'жертва серии',
    profession: 'художница',
    address: 'г. Новоград, ул. Художников, д. 3, кв. 9',
    phone: '+7 (903) 120-04-96',
    email: '',
    avatar: 'М',
    plate: 'А729МС 152',
    car: 'Renault Sandero Stepway',
  },
  {
    id: 'morozov',
    fullName: 'Морозов Алексей Сергеевич',
    contactName: 'Алексей Морозов',
    birthDate: '1971-06-21',
    age: 53,
    status: 'жертва №1',
    profession: 'руководитель отдела закупок',
    address: 'г. Новоград, ул. Лесная, д. 7, кв. 86',
    phone: '+7 (903) 210-06-71',
    email: 'morozov.a@prozrenie.ru',
    avatar: 'А',
    plate: 'Н315МО 152',
    car: 'Nissan Qashqai',
  },
  {
    id: 'krylov',
    fullName: 'Крылов Денис Викторович',
    contactName: 'Денис Крылов',
    birthDate: '1983-11-02',
    age: 41,
    status: 'ложная жертва',
    profession: 'менеджер по продажам',
    address: 'г. Новоград, ул. Садовая, д. 18, кв. 42',
    phone: '+7 (903) 020-11-83',
    email: 'krylov.d@sales.ru',
    avatar: 'Д',
    plate: 'Е642КВ 152',
    car: 'Hyundai Solaris',
  },
  {
    id: 'elena-sokolova',
    fullName: 'Соколова Елена Сергеевна',
    contactName: 'Елена Соколова',
    birthDate: '1959-02-22',
    age: 66,
    status: 'мать Анны',
    profession: 'требует уточнения',
    address: 'г. Новоград, ул. Тихая, д. 4, кв. 2',
    phone: '+7 (903) 220-02-59',
    email: '',
    avatar: 'Е',
    plate: 'В102ЕС 152',
    car: 'Toyota Camry',
  },
  {
    id: 'pavel-sokolov',
    fullName: 'Соколов Павел Владимирович',
    contactName: 'Павел Соколов',
    birthDate: '1956-02-22',
    age: 61,
    status: 'отец Анны, умер в 2017',
    profession: 'основатель региональной сети продуктовых магазинов',
    address: 'г. Новоград, ул. Берёзовая, д. 1',
    phone: '',
    email: '',
    avatar: 'П',
    plate: 'Р777СР 152',
    car: 'LADA Niva Legend',
  },
  {
    id: 'oleg-sokolov',
    fullName: 'Соколов Олег Павлович',
    contactName: 'Олег Соколов',
    birthDate: '1985-12-09',
    age: 39,
    status: 'старший брат Анны',
    profession: 'руководитель семейной сети продуктовых магазинов',
    address: 'г. Новоград, ул. Торговая, д. 6, кв. 112',
    phone: '+7 (903) 090-12-85',
    email: 'oleg.sokolov@retail.ru',
    avatar: 'О',
    plate: 'О555ОС 152',
    car: 'Ford Explorer',
  },
  {
    id: 'maria-egorova',
    fullName: 'Егорова Мария Валентиновна',
    contactName: 'Мария Егорова',
    birthDate: '1983-03-16',
    age: 25,
    status: 'погибшая подруга Анны',
    profession: 'требует уточнения',
    address: 'г. Новоград, ул. Озёрная, д. 6, кв. 12',
    phone: '',
    email: '',
    avatar: 'М',
    plate: 'Т118МЕ 152',
    car: 'LADA Kalina',
  },
  {
    id: 'inna-krestova',
    fullName: 'Крестова Инна Романовна',
    contactName: 'Инна Крестова',
    birthDate: '1983-01-25',
    age: 42,
    status: 'подруга погибшей Марии Егоровой',
    profession: 'требует уточнения',
    address: 'г. Новоград, ул. Цветочная, д. 16, кв. 33',
    phone: '+7 (903) 250-01-83',
    email: '',
    avatar: 'И',
    plate: 'С924КС 152',
    car: 'Nissan Terrano',
  },
  {
    id: 'dmitry-nazarov',
    fullName: 'Назаров Дмитрий Павлович',
    contactName: 'Дмитрий Назаров',
    birthDate: '1984-06-10',
    age: 41,
    status: 'сосед Акуниных, свидетель алиби Жанны',
    profession: 'сосед Акуниных',
    address: 'г. Новоград, ул. Заречная, д. 10',
    phone: '+7 (903) 100-06-84',
    email: '',
    avatar: 'Д',
    plate: 'К201НА 152',
    car: 'Skoda Rapid',
  },
  {
    id: 'ilya-lontsov',
    fullName: 'Лонцов Илья',
    contactName: 'Илья Лонцов',
    birthDate: '',
    age: null,
    status: 'биологический отец Виктора',
    profession: 'связан с табачным складом',
    address: 'г. Новоград, ул. Складская, д. 2, кв. 1',
    phone: '',
    email: '',
    avatar: 'И',
    plate: 'А064ТМ 152',
    car: 'Renault Fluence',
  },
  {
    id: 'nikolai-ivanov',
    fullName: 'Иванов Николай',
    contactName: 'Николай Иванов',
    birthDate: '',
    age: null,
    status: 'приемный отец Виктора',
    profession: 'требует уточнения',
    address: 'г. Новоград, пос. Левинка, ул. Гаражная, д. 7',
    phone: '',
    email: '',
    avatar: 'Н',
    plate: 'В430НК 152',
    car: 'LADA 4x4',
  },
  {
    id: 'oksana-ivanova',
    fullName: 'Иванова Оксана',
    contactName: 'Оксана Иванова',
    birthDate: '',
    age: null,
    status: 'приемная мать Виктора',
    profession: 'требует уточнения',
    address: 'г. Новоград, пос. Левинка, ул. Гаражная, д. 7',
    phone: '',
    email: '',
    avatar: 'О',
    plate: 'М271ОК 152',
    car: 'LADA Granta',
  },
];

const CHARACTER_BY_ID = Object.fromEntries(CHARACTERS.map(c => [c.id, c]));

function getCharacter(id) {
  return CHARACTER_BY_ID[id] || null;
}

function contactFromCharacter(id, colorClass, overrides = {}) {
  const c = getCharacter(id);
  if (!c) return null;
  return {
    name: c.contactName,
    avatar: c.avatar,
    color: colorClass,
    phone: c.phone || '+7 (900) 000-00-00',
    characterId: id,
    ...overrides,
  };
}

function enrichGibddCar(car) {
  const c = getCharacter(car.characterId);
  if (!c) return car;
  return {
    ...car,
    ownerName: c.fullName,
    ownerBirthDate: c.birthDate || car.ownerBirthDate || '',
    ownerAddress: c.address || car.ownerAddress || '',
  };
}

function buildMainPhoneData() {
  // По сюжету телефон принадлежит игрокам: единственный контакт — адвокат Железнов.
  const contacts = [
    { id: 1, name: 'Пётр Железнов', avatar: 'Ж', color: 'avatar-1', phone: '+7 (903) 118-25-00' },
  ];

  return {
    contacts,
    chats: [],
    emails: [],
    callHistory: [],
    games: [
      { id: 'snake', title: 'Змейка', desc: 'Классическая аркада', emoji: '🐍', bg: '#1a472a' },
      { id: 'match3', title: '3 в ряд', desc: 'Скоро', emoji: '🔮', bg: '#3d1a47', disabled: true },
      { id: 'tetris', title: 'Тетрис', desc: 'Скоро', emoji: '🧱', bg: '#2a2a47', disabled: true },
      { id: 'memory', title: 'Память', desc: 'Найди пары', emoji: '🧠', bg: '#2a1a47' },
      { id: 'tap', title: 'Тап-тап', desc: 'Набери очки', emoji: '👆', bg: '#471a2a' },
    ],
    notes: [
      { id: 1, title: 'Адвокат', body: 'Звонить Петровой до среды. Документы по делу передать лично.' },
      {
        id: 2,
        title: 'Машины',
        body: 'Passat А316СК 152 — Сергей\nSanta Fe М042АН 152 — Анна\nПарковка: подземная, «Золотой квадрат».',
      },
      {
        id: 3,
        title: 'Вероника',
        body: 'Granta Е907ВА 152 — проверить в ГИБДД. Не обсуждать с Сергеем при посторонних.',
      },
      {
        id: 4,
        title: 'Жанна',
        body: 'Logan К558ЕН 152 — авто у дома. Похожа со спины на Веронику. Проверить алиби (такси).',
      },
    ],
    calendar: [
      { id: 1, date: '2026-06-22', title: 'Суд по делу Акуниной', time: '10:00' },
      { id: 2, date: '2026-06-26', title: 'Встреча с адвокатом', time: '14:00' },
      { id: 3, date: '2026-06-28', title: 'Осмотр Passat перед судом', time: '11:30' },
    ],
  };
}

function buildAltPhoneData() {
  const contacts = [
    { id: 1, ...contactFromCharacter('artur', 'avatar-1') },
    { id: 2, ...contactFromCharacter('krylov', 'avatar-3') },
    { id: 3, name: 'МИА', avatar: 'М', color: 'avatar-4', phone: '+7 (495) 000-00-01' },
    { id: 4, ...contactFromCharacter('viktor', 'avatar-5') },
    { id: 5, ...contactFromCharacter('natalia', 'avatar-2') },
    { id: 6, name: 'Неизвестный', avatar: '?', color: 'avatar-5', phone: '+7 (900) 000-00-01' },
  ];

  return {
    contacts,
    chats: [
      {
        contactId: 1,
        messages: [
          { text: 'Материалы по KAPNOS готовы. Смотри почту.', sent: false, time: '08:40' },
          { text: 'Получил. Разберусь сегодня.', sent: true, time: '08:42' },
        ],
        unread: true,
      },
      {
        contactId: 2,
        messages: [
          { text: 'Проверьте номер Е907ВА 152 в базе — Granta, Пронина.', sent: false, time: 'Вчера' },
        ],
        unread: true,
      },
      {
        contactId: 6,
        messages: [
          { text: 'Не звони сюда больше', sent: false, time: 'Пн' },
        ],
        unread: false,
      },
    ],
    emails: [
      {
        id: 1,
        from: 'МИА',
        email: 'info@mia.gov',
        subject: 'Справка по делу KAPNOS',
        preview: 'Направляем материалы...',
        time: '09:10',
        unread: true,
        body: 'Направляем материалы по серии KAPNOS.\n\nВо вложении — сводка по номерам ТС и адресам: Морозов (ул. Лесная, 7), Крылов (ул. Садовая, 18).',
        color: 'avatar-4',
      },
      {
        id: 2,
        from: 'Артур Скорый',
        email: 'a.skory@media.ru',
        subject: 'Черновик статьи',
        preview: 'Посмотри формулировки...',
        time: 'Вчера',
        unread: false,
        body: 'Посмотри формулировки в черновике. Не публикуй без согласования.\n\nПорядок жертв перепроверь — Крылов не в серии.',
        color: 'avatar-1',
      },
    ],
    callHistory: [
      { contactId: 1, type: 'incoming', date: 'Сегодня, 08:35' },
      { contactId: 6, type: 'missed', date: 'Пн, 22:14' },
    ],
    games: [],
    notes: [
      {
        id: 1,
        title: 'Номера для проверки',
        body: 'Е907ВА 152 — Granta, Пронина\nВ744КТ 152 — Octavia, Иванов\nТ118МЕ 152 — Kalina, Егорова (2009)',
      },
      {
        id: 2,
        title: 'KAPNOS',
        body: 'Сигарета в правой руке у левши — отметка серии.\nМорозов — ул. Лесная, 7.\nИванов — ProЗрение, ул. Строителей, 9.',
      },
      {
        id: 3,
        title: 'Хронология',
        body: 'Морозов (13.04.2025) → Анна → Мия (19.02.2026).\nКрылов — ложная жертва, не в серии.',
      },
    ],
    calendar: [
      { id: 1, date: '2026-06-22', title: 'Суд по делу Акуниной', time: '10:00' },
      { id: 2, date: '2026-06-24', title: 'Встреча с Артуром', time: '18:30' },
    ],
    photos: [
      { id: 1, title: 'Парковка Морозова', caption: 'Подземная парковка, ул. Лесная, д. 7' },
      { id: 2, title: 'Место аварии 2009', caption: 'Старое Озеро — авария Марии Егоровой' },
    ],
  };
}

window.CharactersDB = {
  CHARACTERS,
  getCharacter,
  contactFromCharacter,
  enrichGibddCar,
  buildMainPhoneData,
  buildAltPhoneData,
};
