/** Локальные данные Novogram — соцсеть Новограда (офлайн). */
window.NovogramSeed = {
  viewerId: 'bestkvestnn',
  auth: {
    username: 'bestkvestnn',
    password: '1234',
  },
  /** Аккаунты, чьи посты составляют ленту новостей */
  newsAccounts: ['novograd_news', 'zheleznov'],
  users: [
    {
      id: 'bestkvestnn',
      username: 'bestkvestnn',
      name: 'Best Kvest NN',
      bio: 'Новоград · квест',
      avatar: 'B',
      color: '#111827',
      posts: 0,
      followers: 12,
      following: 8,
      verified: false,
    },
    {
      id: 'novograd_news',
      username: 'NovogradNews',
      name: 'Новоград News',
      bio: 'Официальная городская лента · новости Новограда',
      avatar: 'N',
      color: '#1d4ed8',
      posts: 3,
      followers: 28400,
      following: 4,
      verified: true,
    },
    {
      id: 'zheleznov',
      username: 'Железнов',
      name: 'Пётр Железнов',
      bio: 'Адвокат · защита по делу Акунина',
      avatar: 'Ж',
      color: '#374151',
      posts: 2,
      followers: 1820,
      following: 46,
      verified: true,
    },
    {
      id: 'sergey_akunin',
      username: 'sergey_akunin',
      name: 'Сергей Акунин',
      bio: 'Новоград · «Золотой квадрат»',
      avatar: 'С',
      color: '#3b82f6',
      posts: 1,
      followers: 412,
      following: 198,
    },
    {
      id: 'anna_akunin',
      username: 'anna_akunin',
      name: 'Анна Акунина',
      bio: 'Риэлтор · объекты Новограда',
      avatar: 'А',
      color: '#ec4899',
      posts: 1,
      followers: 1280,
      following: 340,
    },
    {
      id: 'miya_art',
      username: 'miya.art',
      name: 'Мия',
      bio: 'живопись · улица Художников',
      avatar: 'М',
      color: '#d946ef',
      posts: 1,
      followers: 1450,
      following: 260,
    },
    {
      id: 'artur_skory',
      username: 'artur.skory',
      name: 'Артур Скорый',
      bio: 'журналист · криминальная колонка',
      avatar: 'А',
      color: '#ef4444',
      posts: 0,
      followers: 2100,
      following: 88,
    },
    {
      id: 'veronika_p',
      username: 'veronika.p',
      name: 'Вероника',
      bio: 'Новоград',
      avatar: 'В',
      color: '#a855f7',
      posts: 0,
      followers: 890,
      following: 512,
    },
  ],
  posts: [
    {
      id: 'news_anna',
      userId: 'novograd_news',
      news: true,
      image: {
        category: 'news',
        photo: 12,
        gradient: 'linear-gradient(160deg,#0f172a 0%,#1e3a5f 45%,#64748b 100%)',
        emoji: '📰',
        label: 'Срочно',
      },
      caption:
        'СРОЧНО. Подозреваемый в убийстве супруги задержан. По данным следствия, @sergey_akunin причастен к гибели @anna_akunin. Детали — в полном материале.',
      likes: 4821,
      time: '3 ч',
      comments: [
        {
          id: 'nc1',
          userId: 'zheleznov',
          text: 'Обвинение обязано доказать конкретное преступление. Следим за процессом.',
          time: '2 ч',
        },
        {
          id: 'nc2',
          userId: 'artur_skory',
          text: 'Город ждёт официальной реконструкции.',
          time: '2 ч',
        },
      ],
    },
    {
      id: 'news_miya',
      userId: 'novograd_news',
      news: true,
      image: {
        category: 'art',
        photo: 28,
        gradient: 'linear-gradient(145deg,#4a044e 0%,#86198f 40%,#f0abfc 100%)',
        emoji: '🎨',
        label: 'Город',
      },
      caption:
        'В Новограде обнаружено тело художницы. Полиция подтверждает: погибла @miya.art. Следствие открыто, подробности уточняются.',
      likes: 3104,
      time: '1 д',
      comments: [
        {
          id: 'nc3',
          userId: 'artur_skory',
          text: 'Тяжёлая новость. Не оставляйте дело на «бытовое».',
          time: '20 ч',
        },
        {
          id: 'nc4',
          userId: 'novograd_news',
          text: 'Страница @miya.art сохранена. Следите за обновлениями.',
          time: '18 ч',
        },
      ],
    },
    {
      id: 'news_anna_followup',
      userId: 'novograd_news',
      news: true,
      image: {
        category: 'court',
        photo: 7,
        gradient: 'linear-gradient(180deg,#450a0a 0%,#b91c1c 45%,#fecaca 100%)',
        emoji: '🏛',
        label: 'Суд',
      },
      caption:
        'Дело @anna_akunin: следствие настаивает на версии, что убийство совершил муж, @sergey_akunin. Защита обещает оспорить официальную реконструкцию.',
      likes: 2190,
      time: '2 д',
      comments: [
        {
          id: 'nc5',
          userId: 'zheleznov',
          text: 'Читайте позицию защиты ниже. Версия — не приговор.',
          time: '2 д',
        },
      ],
    },
    {
      id: 'zhel_1',
      userId: 'zheleznov',
      news: true,
      image: {
        category: 'court',
        photo: 33,
        gradient: 'linear-gradient(145deg,#1f2937 0%,#4b5563 50%,#d1d5db 100%)',
        emoji: '⚖',
        label: 'Защита',
      },
      caption:
        'По делу об убийстве @anna_akunin. Обвинение связывает всё с @sergey_akunin. Наша задача — проверить каждое звено официальной версии. Следите за процессом.',
      likes: 967,
      time: '5 ч',
      comments: [
        {
          id: 'zc1',
          userId: 'novograd_news',
          text: 'Запросили комментарий для следующего выпуска.',
          time: '4 ч',
        },
        {
          id: 'zc2',
          userId: 'bestkvestnn',
          text: 'Читаем материалы внимательно.',
          time: '3 ч',
        },
      ],
    },
    {
      id: 'zhel_2',
      userId: 'zheleznov',
      news: true,
      image: {
        category: 'court',
        photo: 41,
        gradient: 'linear-gradient(160deg,#111827 0%,#374151 40%,#9ca3af 100%)',
        emoji: '📎',
        label: 'Позиция',
      },
      caption:
        'Защита не обязана «верить» @sergey_akunin. Мы обязаны сломать слабые места версии по @anna_akunin — там, где обвинение подменяет доказательства выводом.',
      likes: 744,
      time: '1 д',
      comments: [
        {
          id: 'zc3',
          userId: 'artur_skory',
          text: 'Ждём ходатайств по уликам.',
          time: '22 ч',
        },
      ],
    },
    {
      id: 'p_anna',
      userId: 'anna_akunin',
      image: {
        category: 'city',
        photo: 5,
        gradient: 'linear-gradient(145deg,#1e3a5f 0%,#4a7c9b 55%,#c5d5e0 100%)',
        emoji: '🏠',
        label: 'Заречная',
      },
      caption: 'Объект на Заречной. Светлые окна, вид на набережную.',
      likes: 214,
      time: '2 нед',
      comments: [
        { id: 'c1', userId: 'sergey_akunin', text: 'Хороший свет.', time: '2 нед' },
      ],
    },
    {
      id: 'p_sergey',
      userId: 'sergey_akunin',
      image: {
        category: 'car',
        photo: 18,
        gradient: 'linear-gradient(135deg,#166534 0%,#22c55e 50%,#86efac 100%)',
        emoji: '🚗',
        label: 'Passat',
      },
      caption: 'Утро у офиса.',
      likes: 89,
      time: '3 нед',
      comments: [],
    },
    {
      id: 'p_miya',
      userId: 'miya_art',
      image: {
        category: 'art',
        photo: 22,
        gradient: 'linear-gradient(145deg,#581c87 0%,#c026d3 45%,#f0abfc 100%)',
        emoji: '🎨',
        label: 'Холст',
      },
      caption: 'Серия «Лёд». Ещё не закончила.',
      likes: 932,
      time: '3 нед',
      comments: [
        { id: 'c2', userId: 'novograd_news', text: 'Городской репортаж сохранили в архиве.', time: '2 нед' },
      ],
    },
  ],
};
